<a href="https://colab.research.google.com/github/balasaniajay1992/DataScience/blob/main/numpymethods1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create an array of 4x4 zeros
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# to create an array with constant value
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.full((4,4),0,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.full((4,4),-11,dtype=float)

array([[-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.]])

In [ ]:
# Create a numpy array of 4x4 with diagoanl elemets as True and Non diagonal elemets as false
np.identity(4) # Square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
bool(123)

True

In [ ]:
# Create a numpy array of 4x4 with diagoanl elemets as False and Non diagonal elemets as True
~np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
# access diagonal elements of numpy array
np.identity(4)
s=np.identity(4)
s.diagonal


<function ndarray.diagonal>

# **Numpy Slicing and Indexing**

In [ ]:
x=np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[3] # using index we can access one row at a time

array([12, 13, 14, 15])

In [ ]:
x[3][3] # row with element

np.int64(15)

In [ ]:
print(x[3,3])

15


In [ ]:
print(x[4,2],x[5,2])

18 22


In [ ]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [ ]:
# replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# access more rows
x[:] #[start_index:stop_index]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [ ]:
x[3:] # or x[-3:] +ve indexing and -ve indexing will work in indexing

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[::-2]

array([[20, 21, 22, 23],
       [12, 13, 14, 50],
       [ 4,  5,  6,  7]])

In [ ]:
# column operation
x[-2:,-2:] # [row,column]

array([[18, 19],
       [22, 23]])

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[-2:-1,-2:]

array([[18, 19]])

In [ ]:
# Siclicng dynamically cann't Access
 [18
 22,23]