<a href="https://colab.research.google.com/github/balasaniajay1992/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
#  ID
a = np.array([20,10,99,30,100])
a

array([ 20,  10,  99,  30, 100])

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a

array([ 20,  10,  99,  30, 100])

In [ ]:
# find Max number
a.max()

np.int64(100)

In [ ]:
a.min()

np.int64(10)

In [ ]:
a.size # How many elements present

5

In [ ]:
a.ndim

1

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# What is a type of Numpy Array?

In [ ]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [ ]:
b.ndim

2

In [ ]:
# to check no of rows and column
b.shape  # (rows,column)

(3, 3)

In [ ]:
# addition of all elements
b.sum()

np.int64(93)

In [ ]:
print(b.sum())

93


In [ ]:
# columnwise addition
print(b.sum(axis=0))

[16 65 12]


In [ ]:
# Row wise addition
print(b.sum(axis=1))

[31 13 49]


In [3]:
# Assignment: b.min(), b.mean(), b.std()
import numpy as np
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
print(b.mean())

10.333333333333334


In [4]:
print(b.min())

-1


In [6]:
print(b.std())

12.01850425154663


In [ ]:
b = np.array([[10,20,1],
              [-1,5,-9],
              [7,40,5]])
b

array([[10, 20,  1],
       [-1,  5, -9],
       [ 7, 40,  5]])

In [ ]:
print(b.sum())

78


In [ ]:
print(b.sum(axis=1))

[31 -5 52]


In [ ]:
print(b.sum(axis=0))

[16 65 -3]


In [ ]:
# Different ways to create numpy array

In [ ]:
# 1D array
np.random.random(5)

array([0.55436023, 0.61769228, 0.3947198 , 0.28503809, 0.9039159 ])

In [ ]:
# 2D array
np.random.random((5,3))

array([[0.36356468, 0.23989784, 0.23326583],
       [0.18072873, 0.63750826, 0.22696428],
       [0.929177  , 0.37508228, 0.8908534 ],
       [0.70202164, 0.379291  , 0.91699205],
       [0.20369069, 0.10476924, 0.87682182]])

In [ ]:
# 3D Array  (block,row,cloumn)
np.random.random((4,3,3))

array([[[0.80713714, 0.62702323, 0.32626526],
        [0.67919186, 0.05299529, 0.72880741],
        [0.72899111, 0.63591513, 0.05605951]],

       [[0.84612266, 0.81853259, 0.29362481],
        [0.34498335, 0.45899003, 0.13401128],
        [0.6229443 , 0.85578415, 0.70590406]],

       [[0.11972894, 0.86473411, 0.93515388],
        [0.81948588, 0.12601268, 0.697685  ],
        [0.68574314, 0.36948234, 0.17397538]],

       [[0.67408122, 0.5626498 , 0.46143824],
        [0.79696946, 0.27134029, 0.97667861],
        [0.28945486, 0.26141016, 0.90797143]]])

In [ ]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.12/dist-packages/numpy/random/__init__.py'>

In [ ]:
# generarte array with sequence of numbers
c= np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.size

24

In [ ]:
# convert from 1D to 2D
# use reshape() which is temp
c.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
print(c.sum(axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
print(c.sum())

276


In [ ]:
# use resize() used for parmnt  change in dimension
c.resize((3,8))

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
c.shape

(3, 8)

In [ ]:
# Convert nD to 1D --> use ravel()--Temp
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])